version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pc-form
    depends_on:
      - form-db
    environment:
      PMA_HOST: form-db
      PMA_PORT: 3306
      PMA_USER: fujii
      PMA_PASSWORD: fujiidan222
    ports:
      - "8082:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
      
  form-db:
    image: mysql:8.0
    container_name: reception-form
    environment:
      MYSQL_ROOT_PASSWORD: fujiidan222
      MYSQL_DATABASE: form-data
      MYSQL_USER: fujii
      MYSQL_PASSWORD: fujiidan222
    ports:
      - "4407:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  form-web:
    image: httpd:latest
    container_name: pc-reception-form
    ports:
      - "8090:80"
    volumes:
      - ./app:/index.html
      
volumes:
  db_data: